export const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://www.sbs.com.au/food/sites/sbs.com.au.food/files/buttermilk-pancakes.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://img.freepik.com/fotos-premium/hamburguesa-papas-fritas-tabla-cortar_23-2148273000.jpg?w=2000',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://img.imageboss.me/kitchenaid/cdn/animation:true/wp-content/uploads/2021/04/KAD_Blog_MilkShake_1920x1080.png',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://eldiariony.com/wp-content/uploads/sites/2/2022/08/los-5-desayunos-preferidos-de-los-estadounidenses-shutterstock_752274157.jpg?quality=60&strip=all&w=1200',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUE4CdLx524RietozKvJFX7rS2nlFkJ7VOA&usqp=CAU',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://i0.wp.com/www.certifiedpastryaficionado.com/wp-content/uploads/2017/07/Ultimate-Cookies-Cream-Milkshake-6605.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'tartas',
    category: 'breakfast',
    price: 8.99,
    img: 'http://culturavegana.com/wp-content/uploads/2018/03/tarta-de-espinaca-nutrixef-1024x875.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Puttanesca-fd5810c.jpg?resize=960,872?quality=90&resize=556,505',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://t2.uc.ltmcdn.com/pt/posts/4/0/4/como_fazer_milk_shake_6404_600.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
